// py→ts emitter glue (§4): compiles the combined contracts JSON Schema → generated/contracts.ts via
// json-schema-to-typescript. Invoked by aisims_contracts.codegen (the Python entry owns the schema).
// Deterministic: a fixed bannerComment (no timestamp) + sorted $def references + prettier formatting.
import { compile } from 'json-schema-to-typescript';
import { readFileSync, writeFileSync } from 'node:fs';

const [, , schemaPath, outPath] = process.argv;
if (!schemaPath || !outPath) {
  console.error('usage: node emit-ts.mjs <combined.schema.json> <out.ts>');
  process.exit(2);
}

const { $defs = {} } = JSON.parse(readFileSync(schemaPath, 'utf8'));

// A carrier root that references every $def, so json-schema-to-typescript emits all named types
// (consumers import the individual model/enum types; the AISimsContracts carrier is incidental).
const names = Object.keys($defs).sort();
const root = {
  title: 'AISimsContracts',
  type: 'object',
  additionalProperties: false,
  properties: Object.fromEntries(names.map((name) => [name, { $ref: `#/$defs/${name}` }])),
  required: names,
  $defs,
};

const ts = await compile(root, 'AISimsContracts', {
  bannerComment:
    '/* eslint-disable */\n/* AUTO-GENERATED by aisims_contracts.codegen — DO NOT EDIT. */',
  additionalProperties: false,
  declareExternallyReferenced: true,
  format: true,
  style: { semi: true, singleQuote: true },
});

writeFileSync(outPath, ts);
