"""Shared frozen contracts for AI Sims Creator.

Pydantic v2 models are the single source of truth (§2.5, §4): emitted to JSON-Schema
and codegen'd to TS/Node for the desktop UI and the export worker. Every other area
imports from here; this package imports from no other area.
"""

from aisims_contracts.domain import (
    AssetVariant,
    AssetVariantState,
    CleanupStatus,
    CollectionPlan,
    ConceptCandidate,
    ConceptState,
    ExportArtifact,
    ExportMode,
    ExportReport,
    ExportState,
    FunctionalOverlay,
    ItemSpec,
    ItemState,
    MeshCandidate,
    MeshState,
    OverlayState,
    PipelineRun,
    Project,
    ProjectState,
    QaStatus,
    ReviewEvent,
    Severity,
    Step,
    StepState,
    StyleBible,
    Swatch,
    Trace,
    ValidationResult,
    ValidationScope,
    domain_schema,
)
from aisims_contracts.error import ErrorCategory, ErrorCode, ErrorEnvelope
from aisims_contracts.ipc import (
    CONTRACT_VERSION,
    Endpoint,
    GateKind,
    HealthResponse,
    IpcRequestHeaders,
    LogLevel,
    SseEvent,
    ipc_schema,
)

__all__ = [
    "CONTRACT_VERSION",
    "AssetVariant",
    "AssetVariantState",
    "CleanupStatus",
    "CollectionPlan",
    "ConceptCandidate",
    "ConceptState",
    "Endpoint",
    "ErrorCategory",
    "ErrorCode",
    "ErrorEnvelope",
    "ExportArtifact",
    "ExportMode",
    "ExportReport",
    "ExportState",
    "FunctionalOverlay",
    "GateKind",
    "HealthResponse",
    "IpcRequestHeaders",
    "ItemSpec",
    "ItemState",
    "LogLevel",
    "MeshCandidate",
    "MeshState",
    "OverlayState",
    "PipelineRun",
    "Project",
    "ProjectState",
    "QaStatus",
    "ReviewEvent",
    "Severity",
    "SseEvent",
    "Step",
    "StepState",
    "StyleBible",
    "Swatch",
    "Trace",
    "ValidationResult",
    "ValidationScope",
    "domain_schema",
    "ipc_schema",
]
