#!/usr/bin/env bash
# territory-guard.sh — PreToolUse[Edit|Write|NotebookEdit] hook (generated by scaffold-generate).
# Mechanically enforces the orchestrator-territory rule for IMPLEMENTER sessions only.
# The canonical human-readable statement of this list is the "must NOT touch" list in
# each area's CLAUDE.md — this script is its enforcement, not a second source; scaffold-generate
# derives the concrete paths below from the same manifest values.
# No team-registry entry for this session => solo/bootstrap/generation session => no-op.
# Exit 2 blocks the tool call; the stderr message reaches the agent.

set -euo pipefail
command -v jq >/dev/null 2>&1 || exit 0

payload=$(cat)
sid=$(printf '%s' "$payload" | jq -r '.session_id // empty')
reg="$HOME/.claude/team-registry/${sid}.json"
[ -n "$sid" ] && [ -f "$reg" ] || exit 0
role=$(jq -r '.role // empty' "$reg" 2>/dev/null || true)
[ "$role" = "implementer" ] || exit 0

fp=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
[ -n "$fp" ] || exit 0
rel="${fp#"${CLAUDE_PROJECT_DIR:-$PWD}"/}"

# Orchestrator territory — filled from manifest values at generation.
# One pair of entries per code area (<area>/CLAUDE.md + <area>/LESSONS.md), all 6 areas.
TERRITORY=(
  "IMPLEMENTATION_PLAN.md"
  "ARCHITECTURE.md"
  "CLAUDE.md"
  "apps/desktop/CLAUDE.md"
  "apps/desktop/LESSONS.md"
  "services/pipeline/CLAUDE.md"
  "services/pipeline/LESSONS.md"
  "workers/export/CLAUDE.md"
  "workers/export/LESSONS.md"
  "workers/blender/CLAUDE.md"
  "workers/blender/LESSONS.md"
  "packages/contracts/CLAUDE.md"
  "packages/contracts/LESSONS.md"
  "evals/CLAUDE.md"
  "evals/LESSONS.md"
  "docs/briefs/"
  "docs/orchestrator-briefing.md"
  "docs/tdd-brief-template.md"
  "docs/runbooks/"
)

for t in "${TERRITORY[@]}"; do
  case "$rel" in
    "$t" | "$t"*)
      echo "BLOCKED (territory-guard): '$rel' is orchestrator territory — implementers flag it at Step 9 and the orchestrator writes it hot (canonical list: the 'must NOT touch' list in your area's CLAUDE.md)." >&2
      exit 2 ;;
  esac
done

exit 0
