"""
Build monolithic documentation files from shards.

Reads shards from docs/{prd,mvp,tad,api,diagrams}/ and regenerates the
corresponding monolithic files under docs/MONOLITHIC/.

Shards are the source of truth. Monoliths are derived. Run this script
whenever you want a consolidated view (for export, review, or sharing).

Usage:
    python docs/build_monolithic.py

Outputs:
    docs/MONOLITHIC/PRD.md
    docs/MONOLITHIC/MVP_Specification.md
    docs/MONOLITHIC/TAD.md
    docs/MONOLITHIC/API_Specification.md
    docs/MONOLITHIC/Architecture_Diagrams.md
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

DOCS_DIR = Path(__file__).parent
ROOT = DOCS_DIR.parent


@dataclass
class Monolith:
    """Defines how to reassemble a monolithic file from shards."""

    output_filename: str
    shard_subdir: str
    title: str


MONOLITHS = [
    Monolith(
        output_filename="PRD.md",
        shard_subdir="prd",
        title="AI Sims Creator — Product Requirements Document (PRD)",
    ),
    Monolith(
        output_filename="MVP_Specification.md",
        shard_subdir="mvp",
        title="AI Sims Creator — MVP Specification",
    ),
    Monolith(
        output_filename="TAD.md",
        shard_subdir="tad",
        title="AI Sims Creator — Technical Architecture Document (TAD)",
    ),
    Monolith(
        output_filename="API_Specification.md",
        shard_subdir="api",
        title="AI Sims Creator — API Specification",
    ),
    Monolith(
        output_filename="Architecture_Diagrams.md",
        shard_subdir="diagrams",
        title="AI Sims Creator — Architecture Diagrams",
    ),
]


# Regex to strip the shard's front-matter (title + source block + horizontal rule).
# Front-matter looks like:
#   # Title
#
#   > **Source:** ...
#   > Description
#
#   ---
#
FRONT_MATTER_RE = re.compile(
    r"\A\s*"                          # optional leading whitespace
    r"#\s+.+?\n"                      # shard title (H1)
    r"\s*"
    r"(?:>.+?\n\s*)+"                 # one or more blockquote lines (source + description)
    r"---\s*\n",                      # horizontal rule ending front-matter
    re.DOTALL,
)


def strip_front_matter(shard_content: str) -> str:
    """Remove the shard's own front-matter, leaving the body."""
    match = FRONT_MATTER_RE.match(shard_content)
    if not match:
        return shard_content.strip() + "\n"
    body = shard_content[match.end():]
    return body.strip() + "\n"


def build_monolith(monolith: Monolith, docs_dir: Path) -> Path:
    """Read all shards for one monolith and write the consolidated file."""
    shard_dir = docs_dir / monolith.shard_subdir
    if not shard_dir.is_dir():
        raise FileNotFoundError(f"Shard directory missing: {shard_dir}")

    # Shards are ordered by their leading numeric prefix (00-, 01-, etc.)
    shard_files = sorted(shard_dir.glob("*.md"))
    if not shard_files:
        raise FileNotFoundError(f"No shard files found in {shard_dir}")

    parts: list[str] = []
    parts.append(f"# {monolith.title}\n")
    parts.append(
        f"> **Regenerated from shards.** Source of truth is the individual shard files "
        f"under `docs/{monolith.shard_subdir}/`. Do not edit this file directly; edits "
        f"will be overwritten the next time `docs/build_monolithic.py` is run.\n"
    )
    parts.append("---\n")

    # Special case for MVP: the phase shards (§9.1–§9.8) don't individually carry a
    # §9 parent header because they were split out during sharding. Inject one so the
    # regenerated monolith preserves the original §9 "Phase Task Breakdown" structure.
    #
    # We match files like `05-phase-0-foundation.md` but NOT `01-phase-overview.md`
    # by requiring a digit after "phase-".
    phase_shard_re = re.compile(r"-phase-\d+-")
    injected_phase_header = False
    for shard_path in shard_files:
        if (
            monolith.shard_subdir == "mvp"
            and not injected_phase_header
            and phase_shard_re.search(shard_path.name)
        ):
            parts.append(
                "## 9. Phase Task Breakdown\n\n"
                "Tasks below are scoped for Claude Code consumption. Each task "
                "includes outputs, dependencies, and acceptance criteria. Claude "
                "Code is expected to further decompose tasks into subtasks at "
                "implementation time.\n\n"
                "Tasks are numbered `{phase}.{task}` for cross-reference.\n"
            )
            injected_phase_header = True

        raw = shard_path.read_text(encoding="utf-8")
        body = strip_front_matter(raw)
        parts.append(body)
        parts.append("\n")

    out_dir = docs_dir / "MONOLITHIC"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / monolith.output_filename

    content = "\n".join(parts).rstrip() + "\n"
    out_path.write_text(content, encoding="utf-8")
    return out_path


def main() -> None:
    produced: list[Path] = []
    for monolith in MONOLITHS:
        out_path = build_monolith(monolith, DOCS_DIR)
        produced.append(out_path)
        print(f"Built {out_path.relative_to(ROOT)}")

    print(f"\n{len(produced)} monoliths regenerated from shards.")


if __name__ == "__main__":
    main()
