#!/usr/bin/env bash
# PreToolUse hook: block edits to auto-generated files.
#
# Triggered on: Write, Edit, MultiEdit
# Blocks when:
#   - Target file is under shared-types/ (generated by scripts/generate_types.py)
#   - Target file is under docs/MONOLITHIC/ (generated by docs/build_monolithic.py)
#
# Exit code 2 = block the action. Claude Code surfaces stderr to the model.
# Exit code 0 = allow.

set -euo pipefail

# Read the tool call JSON from stdin
INPUT=$(cat)

# Extract file_path from the tool input. Handles Write, Edit, MultiEdit.
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.path // empty')

if [[ -z "$FILE_PATH" ]]; then
    # No file path in this tool call — not something we guard. Allow.
    exit 0
fi

# Normalize to a path relative to project root if absolute
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
if [[ "$FILE_PATH" == "$PROJECT_DIR/"* ]]; then
    REL_PATH="${FILE_PATH#"$PROJECT_DIR/"}"
else
    REL_PATH="$FILE_PATH"
fi

case "$REL_PATH" in
    shared-types/*)
        echo "BLOCKED: $REL_PATH is auto-generated by scripts/generate_types.py." >&2
        echo "Edit the corresponding Pydantic schema in sidecar/aisc/schemas/ and re-run codegen instead." >&2
        exit 2
        ;;
    docs/MONOLITHIC/*)
        echo "BLOCKED: $REL_PATH is auto-generated by docs/build_monolithic.py." >&2
        echo "Edit the corresponding shard in docs/{prd,mvp,tad,api,diagrams}/ instead." >&2
        exit 2
        ;;
esac

# Allow everything else
exit 0
